// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uppgifter_IdentityAndSession.Data;

namespace Uppgifter_IdentityAndSession.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20211105121012_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Uppgifter_IdentityAndSession.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "AMD Ryzen 5900X",
                            Price = 6000.0
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "NVIDIA RTX 3080",
                            Price = 99999.0
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Samsung 970 EVO 250gb",
                            Price = 1000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
